// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVKeYxFs-a26zwRRhn80bsFMZA-02YIwg',
    appId: '1:1045433698608:web:351eb572a9ae0c502560f5',
    messagingSenderId: '1045433698608',
    projectId: 'sam-r24',
    authDomain: 'sam-r24.firebaseapp.com',
    storageBucket: 'sam-r24.firebasestorage.app',
    measurementId: 'G-65FM2RWCCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7DvtgmAI6uAv3IWq0Np1fNfN1N2O8u_o',
    appId: '1:1045433698608:android:8e6b2b98252a692a2560f5',
    messagingSenderId: '1045433698608',
    projectId: 'sam-r24',
    storageBucket: 'sam-r24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNJezq0vDSn3cKsvv4LZAGYNNcPhGncYY',
    appId: '1:1045433698608:ios:7462cbe7c1a9a5c32560f5',
    messagingSenderId: '1045433698608',
    projectId: 'sam-r24',
    storageBucket: 'sam-r24.firebasestorage.app',
    iosBundleId: 'com.example.samRemastered',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNJezq0vDSn3cKsvv4LZAGYNNcPhGncYY',
    appId: '1:1045433698608:ios:7462cbe7c1a9a5c32560f5',
    messagingSenderId: '1045433698608',
    projectId: 'sam-r24',
    storageBucket: 'sam-r24.firebasestorage.app',
    iosBundleId: 'com.example.samRemastered',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVKeYxFs-a26zwRRhn80bsFMZA-02YIwg',
    appId: '1:1045433698608:web:81ab37fcbcd1a3a32560f5',
    messagingSenderId: '1045433698608',
    projectId: 'sam-r24',
    authDomain: 'sam-r24.firebaseapp.com',
    storageBucket: 'sam-r24.firebasestorage.app',
    measurementId: 'G-2J1PR42LVN',
  );
}
